name: hyper-net
channels:
    - conda-forge
dependencies:
  - python
  - pylint
  - pandas
  - scipy
  - tldr
  - matplotlib
  - jupyterlab
  - numpy
  - pip
  - pip:
    - hypernetx
    - toponetx
    - networkx
